module.exports = [
    "Buy groceries",
    "Finish project report",
    "Call mom",
    "Schedule dentist appointment",
    "Plan weekend trip",
    "Organize workspace",
    "Write blog post",
    "Clean the kitchen",
    "Pay electricity bill",
    "Water the plants",
    "Prepare presentation",
    "Update resume",
    "Read new book",
    "Respond to emails",
    "Backup computer files",
    "Wash the car",
    "Renew library books",
    "Research investment options",
    "Plan birthday party",
    "Buy new headphones",
    "Fix leaky faucet",
    "Practice guitar",
    "Attend yoga class",
    "Update software",
    "Order birthday gift",
    "Organize photo album",
    "Take out trash",
    "Prepare dinner",
    "Check tire pressure",
    "Send thank you notes",
    "Meditate",
    "Review budget",
    "Schedule team meeting",
    "Get a haircut",
    "Finish online course",
    "Plan family gathering",
    "Write a poem",
    "Check credit score",
    "Set up a savings plan",
    "Clean the garage",
    "Update website",
    "Plan date night",
    "Buy new shoes",
    "Walk the dog",
    "Visit grandparents",
    "Try new recipe",
    "Practice coding",
    "Volunteer at shelter",
    "Organize closet",
    "Schedule eye exam",
];
