module.exports = [
    "Buy milk, eggs, bread, and vegetables",
    "Compile the data and summarize findings",
    "Chat with mom about upcoming plans",
    "Book an appointment for next week",
    "Research and book a nice place to visit",
    "Sort through papers and tidy up",
    "Write about the latest tech trends",
    "Clean the stove, countertops, and fridge",
    "Pay the bill online before the due date",
    "Water all indoor and outdoor plants",
    "Prepare slides and practice speaking",
    "Add latest work experience and skills",
    "Start reading 'The Great Gatsby'",
    "Reply to all pending work emails",
    "Create a backup on an external drive",
    "Wash and vacuum the car interior",
    "Renew the books before they are due",
    "Look into stocks and mutual funds",
    "Plan activities and invite friends",
    "Find a good quality pair with noise cancellation",
    "Replace the washer in the faucet",
    "Practice chords and a new song",
    "Attend the 6 PM class at the studio",
    "Install the latest updates for security",
    "Choose and order a thoughtful gift",
    "Organize and label all photos",
    "Collect and dispose of all trash",
    "Cook a healthy meal for the family",
    "Ensure all tires are properly inflated",
    "Write and send notes to friends",
    "Spend 10 minutes meditating",
    "Review and adjust monthly expenses",
    "Send invites and prepare agenda",
    "Schedule an appointment for this week",
    "Complete all modules and take the final exam",
    "Plan the menu and activities",
    "Write a short poem on nature",
    "Request a credit report from the bank",
    "Open a savings account and set goals",
    "Clean out old items and reorganize",
    "Update content and design",
    "Plan a fun and romantic evening",
    "Buy a comfortable and stylish pair",
    "Take the dog to the park",
    "Visit and spend quality time with them",
    "Try making homemade pasta",
    "Work on a new coding project",
    "Sign up and volunteer this weekend",
    "Sort clothes and donate whats not needed",
    "Book an appointment for an eye checkup",
];
